//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecognizeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecognizeStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prototype.Resources.RecognizeStrings", typeof(RecognizeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die バック ähnelt.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 閉めます ähnelt.
        /// </summary>
        internal static string closeMasu {
            get {
                return ResourceManager.GetString("closeMasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 閉める ähnelt.
        /// </summary>
        internal static string closeRu {
            get {
                return ResourceManager.GetString("closeRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 閉めて ähnelt.
        /// </summary>
        internal static string closeTe {
            get {
                return ResourceManager.GetString("closeTe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 閉めてください ähnelt.
        /// </summary>
        internal static string closeTekudasai {
            get {
                return ResourceManager.GetString("closeTekudasai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 行きます ähnelt.
        /// </summary>
        internal static string goMasu {
            get {
                return ResourceManager.GetString("goMasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 行く ähnelt.
        /// </summary>
        internal static string goRu {
            get {
                return ResourceManager.GetString("goRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 文法の練習 ähnelt.
        /// </summary>
        internal static string grammarExercise {
            get {
                return ResourceManager.GetString("grammarExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 文法の説明 ähnelt.
        /// </summary>
        internal static string grammarExplanation {
            get {
                return ResourceManager.GetString("grammarExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die へ ähnelt.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die メニュー ähnelt.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 開けます ähnelt.
        /// </summary>
        internal static string openMasu {
            get {
                return ResourceManager.GetString("openMasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 開ける ähnelt.
        /// </summary>
        internal static string openRu {
            get {
                return ResourceManager.GetString("openRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 開けて ähnelt.
        /// </summary>
        internal static string openTe {
            get {
                return ResourceManager.GetString("openTe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 開けてください ähnelt.
        /// </summary>
        internal static string openTekudasai {
            get {
                return ResourceManager.GetString("openTekudasai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die オプション ähnelt.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die プログラム ähnelt.
        /// </summary>
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die この窓 ähnelt.
        /// </summary>
        internal static string thisWindow {
            get {
                return ResourceManager.GetString("thisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die を ähnelt.
        /// </summary>
        internal static string wo {
            get {
                return ResourceManager.GetString("wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ことばの練習 ähnelt.
        /// </summary>
        internal static string wordsExercise {
            get {
                return ResourceManager.GetString("wordsExercise", resourceCulture);
            }
        }
    }
}
